Repository JabRef/user-documentation, pull requests merged in 2019-10, with the labels that each got.

#219 Documentation Changes
  README.md
  en/ACMPortal.md
  en/ADS.md
  en/Autosave.md
  en/Backup.md
Labels: waiting for feedback

#230 Update README.md
  README.md
Labels: invalid

#231 Update status.md
  status.md
Labels: invalid

#239 Added documentation for drag and drop behaviors
  en/EntryEditor.md
Labels: ready-for-review
