Repository JabRef/user-documentation, pull requests merged in 2020-03, with the labels that each got.

#259 Description of the Edit group window
  en/finding-sorting-and-cleaning-entries/groups.md
Labels: ready-for-review

#258 Reworked general FAQ
  en/faq/faqgeneral.md
Labels: ready-for-review

#263 New QA: Search feature in preferences
  en/faq/faqgeneral.md
Labels: ready-for-review

#261 Portable version: not only zip
  en/faq/faqgeneral.md
Labels: enhancement, ready-for-review

#262 New Q&A: Testing the dev version without uninstalling the release one
  en/faq/faqgeneral.md
Labels: enhancement
